server.port=8001

spring.datasource.url=jdbc:h2:mem:subscriptiondb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
app.admin.bootstrap-enabled=true
app.admin.name=Kavya Iyer
app.admin.email=admin@planpilot.in
app.admin.company=PlanPilot Operations
app.admin.password=password123
app.admin.update-password-on-startup=true
